### ISSUE TITLE
Please share the dataset - "restaurants_new.csv", thanks

### ISSUE THREAD

**Issue by johnhhu2020** [vhsenna/datacamp-courses#1]
Just saw your kindly shared the Jupyter Notes, its great to find such valuable material on cleaning dirty data.  

Thus having  no datasets makes it hard to image what is happening under those codes.  So can you please share the datasets mentioned in you notebook?  

So many thanks.

**Comment by vhsenna** [comment]
The dataset is already uploaded in the repository https://github.com/vhsenna/datacamp-courses/blob/main/cleaning_data_in_python/datasets/restaurants_new.csv

**Comment by vhsenna** [comment]
The dataset is already uploaded to the repository https://github.com/vhsenna/datacamp-courses/blob/main/cleaning_data_in_python/datasets/restaurants_new.csv
